import './global.css';

export const metadata = {
  title: 'SOLBER - Добыча строительных материалов',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className="min-h-screen flex flex-col">{children}</body>
    </html>
  );
}
