import { Career, CareerStatus, MaterialType } from './types';

export const MOCK_CAREERS: Career[] = [
  {
    id: '1',
    status: CareerStatus.ACTIVE,
    name: 'АГАТ',
    region: 'Владимирская',
    district: 'Александровский',
    address:
      'деревня Корякино, муниципальное Карабановское во Владимирской области, Россия',
    description:
      'Крупный карьер по добыче строительного камня. Современное оборудование и высокие стандарты безопасности.',
    materials: 'Гравий, Песок',
    materialTypes: [
      MaterialType.GRAVEL,
      MaterialType.SAND_QUARRY,
      MaterialType.CRUSHED_GRAVEL,
    ],
    slug: 'agat-karabanovskoe',
    contactPerson: 'Иванов Сергей Петрович',
    phone: '+7 (920) 123-45-67',
    email: 'info@agat-career.ru',
  },
  {
    id: '2',
    status: CareerStatus.ACTIVE,
    name: 'Карьер Северный',
    region: 'Московская',
    district: 'Дмитровский',
    address: 'поселок Северный, Московская область, Россия',
    description:
      'Карьер специализируется на добыче песчано-гравийной смеси высокого качества.',
    materials: 'ПГС, Песок, Щебень',
    materialTypes: [
      MaterialType.SHPS_PGS,
      MaterialType.SAND_WASHED,
      MaterialType.CRUSHED_GRAVEL,
    ],
    slug: 'severny',
    contactPerson: 'Петров Алексей Николаевич',
    phone: '+7 (495) 234-56-78',
    email: 'sales@severny-career.ru',
  },
  {
    id: '3',
    status: CareerStatus.CLOSED,
    name: 'Южный горизонт',
    region: 'Тульская',
    district: 'Узловский',
    address: 'село Большое Поле, Тульская область, Россия',
    description:
      'Разрабатываемое месторождение с перспективными запасами строительных материалов.',
    materials: 'Известняк, Доломит',
    materialTypes: [MaterialType.CRUSHED_LIMESTONE, MaterialType.DOLOMITE],
    slug: 'yuzhny-gorizont',
    contactPerson: 'Сидоров Михаил Владимирович',
    phone: '+7 (487) 345-67-89',
    email: 'contact@ugorizont.ru',
  },
  {
    id: '4',
    status: CareerStatus.ACTIVE,
    name: 'Волга-Камень',
    region: 'Нижегородская',
    district: 'Павловский',
    address: 'деревня Каменка, Нижегородская область, Россия',
    description:
      'Один из старейших карьеров региона с богатыми запасами гранита.',
    materials: 'Гранит, Щебень различных фракций',
    materialTypes: [MaterialType.CRUSHED_GRANITE, MaterialType.SCREENINGS],
    slug: 'volga-kamen',
    contactPerson: 'Кузнецов Дмитрий Александрович',
    phone: '+7 (831) 456-78-90',
    email: 'zakaz@volga-kamen.ru',
  },
  {
    id: '5',
    status: CareerStatus.CLOSED,
    name: 'Восточный',
    region: 'Владимирская',
    district: 'Гороховецкий',
    address: 'село Восточное, Владимирская область, Россия',
    description:
      'Временно законсервированный карьер. Планируется возобновление работ.',
    materials: 'Песок',
    materialTypes: [MaterialType.SAND_ALLUVIAL, MaterialType.SAND_SCREENED],
    slug: 'vostochny',
    contactPerson: 'Морозов Игорь Викторович',
    phone: '+7 (492) 567-89-01',
    email: 'info@vostochny-career.ru',
  },
  {
    id: '6',
    status: CareerStatus.ACTIVE,
    name: 'Кварцит-Центр',
    region: 'Ярославская',
    district: 'Ростовский',
    address: 'поселок Кварцитный, Ярославская область, Россия',
    description: 'Современный карьерный комплекс с полным циклом переработки.',
    materials: 'Кварцит, Щебень, Отсев',
    materialTypes: [
      MaterialType.SAND_QUARTZ,
      MaterialType.CRUSHED_GRANITE,
      MaterialType.SCREENINGS,
    ],
    slug: 'kvarcit-centr',
    contactPerson: 'Соловьев Андрей Геннадьевич',
    phone: '+7 (485) 678-90-12',
    email: 'sales@kvarcit-center.ru',
  },
];
